name: Work 2
on:
  push:
    branches:
      - test_1
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Impresion 1
        run: echo "Impresion 1"
      - name: Impresion 2
        run: echo "Impresion 2"
      - name: Impresion 3
        run: echo "Impresion 3"

